version: '3.4'
services:
  taildawg:
    stdin_open: true
    build:
      context: .
      dockerfile: dockerfile
    expose:
      - 8090
    ports:
      - 8090:80
    environment:
      - CHOKIDAR_USEPOLLING=true