/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 public/models/DELTA.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/DELTA.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Text.geometry} material={nodes.Text.material} position={[0, 0, 0.333]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
    </group>
  )
}

useGLTF.preload('/DELTA.glb')
